- name: Copy {{COMPONENT}} code.sh
  ansible.builtin.copy:
    src: code.sh
    dest: /tmp/code.sh

- name: install {{COMPONENT}}
  ansible.builtin.shell: source /tmp/code.sh

- name: Copy {{COMPONENT}} code.sh
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat Service