- name: Copy {{COMPONENT}} code.sh
  ansible.builtin.copy:
    src: code.sh
    dest: /tmp/code.sh

- name: install {{COMPONENT}}
  ansible.builtin.shell: source /tmp/code.sh

- name: copy {{COMPONENT}} config file
  ansible.builtin.template:
    src: "{{ item.file }}"
    dest: "{{item.dest}}"
  with_items:
    - { file: 'filebeat.yml' , dest: '/etc/filebeat/filebeat.yml'}
  notify: restart Service