# yum install epel-release yum-utils -y
# yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
# yum-config-manager --enable remi
# yum install redis -y

- name: install repo
  ansible.builtin.yum_repository:
    name:
      - remi-release-7
    description: custom repositories
    baseurl: https://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: install release
  ansible.builtin.yum:
    name:
      - epel-release
      - yum-utils
      - remi-release-7
    state: installed

