- name: docker community edition and docker compose setup
  import_tasks: docker.yaml

- name:  Copy {{ COMPONENT }} reverse proxy configuration & docker compose file
  become: true
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
  - { src: 'Dockerfile' , dest: '/home/{{ansible_user_id}}/{{COMPONENT}}/nginx/' }
  - { src: 'docker-compose.yml' , dest: '/home/{{ansible_user_id}}/{{COMPONENT}}/' }

- name:
  ansible.builtin.template:
    src: default.conf
    dest: /home/{{ansible_user_id}}/{{COMPONENT}}/nginx/
