- name: Install EPEL repo
  yum:
    name: epel-release
    state: present

- name: Ensure nginx is Installed
  ansible.builtin.yum:
    name:
      - nginx
    state: present
  notify: Enable and Start the Service

- name: current enforce(getenforce) 'Enforcing' changing to 'Permissive'
  ansible.builtin.shell:
    cmd: setenforce Permissive

- name: Copy {{ COMPONENT }} reverse proxy configuration
  ansible.builtin.template:
    src:  "{{item.file}}"
    dest: "{{item.dest}}"
  with_items:
    - { file: 'nodejs.conf', dest: '/etc/nginx/conf.d/nodejs.conf' }
    - { file: 'nginx.conf', dest: '/etc/nginx/nginx.conf' }
  notify: restart nginx Service

#- name: httpd network on
#  ansible.builtin.shell:
#    cmd: setsebool -P httpd_can_network_connect on