# add repo  vi /etc/yum.repos.d/mongodb.repo

# [mongodb-org-4.4]
#name=MongoDB Repository
#baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.4/x86_64/
#gpgcheck=1
#enabled=1
#gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc

# yum install -y mongodb-org
# systemctl enable mongod
# systemctl start mongod

# Update Liste IP address from 127.0.0.1 to 0.0.0.0 in config file
# Config file: /etc/mongod.conf
# then restart the service
# systemctl restart mongod

# Download the schema and load it.
# curl -s -L -o /tmp/mongodb.zip "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"
# cd /tmp
# unzip mongodb.zip
# cd mongodb-main
# load mongodb schema
# mongo < catalogue.js
# mongo < users.js

- name: adding mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mangodb
  ansible.builtin.yum:
    name:
      - mongodb-org
      - unzip
    state: present

# replace bindIp: 127.0.0.1 -> 0.0.0.0
- name: Replace ip address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    after: 'bindIp:'
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    backup: yes

- name: start service
  ansible.builtin.systemd:
    state: started
    name: mongod
    enabled: yes

- name: download mongodb schema
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: load catalogue schma
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes

- name: load users schma
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes