- hosts: JENKINS
  become: yes
  tags: jenkins
  roles:
    - jenkins
    - node_exporter

- hosts: SONAR
  become: yes
  roles:
    - sonar
    - node_exporter

- hosts: NEXUS
  tags: nexus
  become: yes
  roles:
    - nexus
    - node_exporter

- name: slave setup
  hosts: WORK-STATION
  become: yes
  tags: slave
  roles:
    - workstation
    - node_exporter

- name: prometheus setup
  hosts: PRO
  become: yes
  tags: pro
  roles:
    - prometheus

- name: grafana setup on workstation
  hosts: WORK-STATION
  become: yes
  tags: grafana
  roles:
    - grafana

- name: grafana setup on workstation
  hosts: ELK
  become: yes
  tags: elk
  roles:
    - elk