- hosts: JENKINS
  become: yes
  roles:
    - jenkins
- hosts: SONAR
  become: yes
  roles:
    - sonar
- hosts: NEXUS
  tags: nexus
  become: yes
  roles:
    - nexus

- name: slave setup
  hosts: WORK-STATION
  become: yes
  tags: slave
  roles:
    - workstation

- name: prometheus setup
  hosts: PRO
  become: yes
  tags: pro
  roles:
    - prometheus