# Example that prints the loopback address and gateway for each host
- name: Print the gateway for each host when defined
  hosts: all
  become: true
  tasks:
    - ansible.builtin.debug:
        msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}

    - ansible.builtin.command: uptime
      register: result

    - ansible.builtin.debug:
        msg: "result is : {{ result.stdout }}"