# Example that prints the loopback address and gateway for each host
- name: Print the gateway for each host when defined
  hosts: all
  become: true
  tasks:
    - ansible.builtin.debug:
        msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
        when: ansible_default_ipv4.gateway is defined

    - ansible.builtin.shell: /usr/bin/uptime
      register: result

    - ansible.builtin.debug:
        var: result
        verbosity: 2

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 4