#sudo wget -O /etc/yum.repos.d/jenkins.repo \
#    https://pkg.jenkins.io/redhat-stable/jenkins.repo
#sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
#sudo yum upgrade
## Add required dependencies for the jenkins package
#sudo yum install java-11-openjdk
#sudo yum install jenkins
#sudo systemctl daemon-reload
---
- hosts: jenkins
  become: yes
  vars:
    apps:
      - jenkins
      - firewalld
      - git
  tasks:
    - name: Ensure Jenkins Repository is Installed
      yum_repository:
        name: jenkins
        state: present
        description: Official Jenkins Yum Repo
        baseurl: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        gpgcheck: yes
        enabled: yes
    - name: Ensure java & Jenkins is Installed
      yum :
        name:
          - firewalld
          - java-11-openjdk
          - jenkins
        state: present
    - name: Enable and Start the Service
      loop: "{{ apps }}"
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
    - name: Open Firewall Port
      firewalld:
        zone: public
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: true
    - name: Enable and Start the firewalld Service
      service:
        name: firewalld
        enabled: yes
        state: restarted