- name: setup work_station
  become: yes
  hosts: work_station
  tags: work_station
  roles:
    - link


- name: setup frontend
  become: yes
  hosts: FRONTEND
  tags: frontend
  roles:
    - link
    - frontend

- name: mongodb installation
  become: yes
  hosts: MONGODB
  tags: mongodb
  roles:
    - link
    - mongodb

- name: catalague setup
  become: yes
  hosts: CATALOGUE
  tags: catalogue
  roles:
    - catalogue
    - link

- name: redis setup
  become: yes
  hosts: REDIS
  tags: redis
  roles:
    - link
    - redis

- name: user setup
  become: yes
  hosts: USER
  tags: user
  roles:
    - user