- name: setup frontend
  become: yes
  hosts: FRONTEND
  tags: frontend
  roles:
    - link
    - frontend

- name: mongodb installation
  become: yes
  hosts: MONGODB
  roles:
    - link
    - mongodb