- name: nginx reverse proxy setup for nodejs
  hosts: INTERNET-FACING
  tags: nginx
  vars:
    - COMPONENT: nodejs
  become: yes
  roles:
    - nginx

- hosts: WORK-STATION
  become: yes
  roles:
    - nodejs
- hosts: JENKINS
  become: yes
  roles:
    - jenkins
- hosts: sonar
  become: yes
  roles:
    - sonar