- name: nginx reverse proxy setup for nodejs
  hosts: INTERNET-FACING
  tags: nginx
  vars:
    - COMPONENT: nodejs
    - SERVICE: nodejs-internal #  nodejs-internal-dev.chaitu.org:8080
    - ENV: dev
    - DOMAIN: chaitu.org
  become: yes
  roles:
    - nginx
    - node_exporter


- name: nodejs internal install with dependencyes
  hosts: NODEJS-INTERNAL
  become: yes
  tags: nodejs
  roles:
    - nodejs
    - node_exporter
    - filebeat