- name: setup frontend
  become: yes
  hosts: FRONTEND
  tags: frontend
  roles:
    - link
    - frontend

- name: mongodb installation
  become: yes
  hosts: MONGODB
  tags: mongodb
  roles:
    - link
    - mongodb

- name: catalague setup
  become: yes
  hosts: CATALOGUE
  tags: catalogue
  roles:
    - catalogue
    - link
