--- #start of yml file
#start with - (dash)
- name: install required software on WebServer
  hosts: WebServer #two spaces
  become: true
  tasks:
    - name: creating a user test
      user:
        name: test
        state: present