---
- name:  create multiple users
  hosts: WebServer
  become: yes
  vars:
    users:
      - chaitanya
      - chandra
      - chaitu
      - chay
  tasks:
    - name: creating users by using loop
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"