---
- name:  create multiple users
  hosts: WebServer
  become: yes
  vars:
    web_users:
      - chaitanya
      - chandra
    db_users:
      - chaitu
      - chay
  tasks:
    - name: creating database users  using loop and magic variable
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ db_users }}"
      when: "'databaseServer' in group_names"
    - name: creating web users using loop and magic variable
      user:
        name: "{{ item }}"
        state: absent
      loop: "{{ web_users }}"
      when: "'WebServer' in group_names"
      # magic variable (group_names)[list of all groups in workspace].