- name: Add Application User
  ansible.builtin.user:
    name: "{{USER}}"
  register: app_user_info

- name: Download and UnZip the {{COMPONENT}} Content
  ansible.builtin.unarchive:
    src: https://github.com/ChaitanyaChandra/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes
  when: GIT_DOWNLOAD is defined

- name: Download {{NEXUS_COMPONENT}} from Nexus
  ansible.builtin.get_url:
    url: http://nexus-dev.chaitu.org:8081/repository/{{NEXUS_COMPONENT}}/{{NEXUS_COMPONENT}}-{{APP_VERSION}}.zip
    dest: /tmp
    username: "{{NEXUS_USERNAME}}"
    password: "{{NEXUS_PASSWORD}}"
  when: GIT_DOWNLOAD is not defined

## This is been added for deployment purpose , For first time when component is setup then it might fail, So lets ignore the failure
- name: Stop {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: stopped
  ignore_errors: yes

- name: Remove Old App Content
  ansible.builtin.file:
    path: /home/{{USER}}/{{COMPONENT}}
    state: absent

- name: Create App Dir
  ansible.builtin.file:
    path: /home/{{USER}}/{{COMPONENT}}
    state: directory
  become_user: "{{USER}}"

- name: Copy App Content
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{USER}}/{{COMPONENT}}/
    remote_src: yes
  become_user: "{{USER}}"