- name: install nodejs, make , gcc-c++
  ansible.builtin.yum:
    name:
      - unzip
      - make
      - gcc-c++
      - nodejs
    state: installed

- name: create user roboshop
  ansible.builtin.user:
    name: roboshop
    state: present

- name: download nodejs files
  ansible.builtin.import_role:
    name: common
    tasks_from: download

# delete previous nodejs files
- name: check catalogue exists
  stat: path=/tmp/catalogue
  register: myfile_stat
- name: if catalogue exists delete
  command: rm -rf /tmp/catalogue
  when: myfile_stat.stat.exists

# move the file if exists
- name: check catalogue-main if exists
  stat: path=/tmp/catalogue-main
  register: file_stat
- name: if catalogue-main exists remane to catalogue
  command: mv /tmp/catalogue-main /tmp/catalogue
  when: file_stat.stat.exists

# copy files to home dir
- name: copy files to home dir
  ansible.builtin.copy:
    src: /tmp/catalogue
    dest: /home/roboshop/
    remote_src: yes

# npm install
- name: npm install
  community.general.npm:
    path: /home/roboshop/catalogue/

# mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service
- name: copy catalogue config template
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd:
    name: nodejs
    enabled: yes
    state: started
    daemon_reload: yes