- name: copy python script
  ansible.builtin.template:
    src: code.py
    dest: /tmp/code.py
  ignore_errors: yes

- name: exec python script
  ansible.builtin.shell: python3 /tmp/code.py
  register: fqdn_list

- name: print fqdn list
  debug:
    msg: "{{fqdn_list.stdout}}"