- name: Set Hostname
  ansible.builtin.shell:  hostnamectl set-hostname {{COMPONENT}}-{{ENV}}

- name:  Copy {{COMPONENT}} installation files and alert file
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'code.sh' , dest: '/tmp/code.sh' }
    - { src: 'alert.sh' , dest: '/tmp/alert.sh' }

- name: install {{COMPONENT}}
  ansible.builtin.shell:  source /tmp/code.sh ; source /tmp/alert.sh

- name: Install EPEL repo
  yum:
    name: epel-release
    state: present

- name: Ensure nginx is Installed
  ansible.builtin.yum :
    name:
      - git
      - nginx
      - python3
    state: present

- name: current enforce(getenforce) 'Enforcing' changing to 'Permissive'
  ansible.builtin.shell:
    cmd: setenforce Permissive
  ignore_errors: yes

- name: Copy {{COMPONENT}} reverse proxy configuration
  ansible.builtin.template:
    src: pro.conf
    dest: /etc/nginx/conf.d/pro.conf
  notify: restart nginx Service

- name:  Copy {{COMPONENT}} configuration
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'prometheus.yml' , dest: '/opt/prometheus/prometheus.yml' }
    - { src: 'rules.yml' , dest: '/opt/prometheus/rules.yml' }
    - { src: 'alerts.yml' , dest: '/opt/prometheus/alerts.yml' }
    - { src: 'app-alerts.yml' , dest: '/opt/prometheus/app-alerts.yml' }
    - { src: 'ses.yml' , dest: '/opt/prometheus/ses.yml' }

  notify: restart prometheus Service

#- name: docker community edition and docker compose setup
#  import_tasks: fqdn.yaml