- name:  restart prometheus Service
  ansible.builtin.systemd: name={{ item.service }}  state='restarted'
  with_items:
    - { service: 'prometheus' }
    - { service: 'alertmanager' }

- name: restart nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted