groups:
  - name: custom
    rules:
      - record: {{SERVICE}}_memory_used_percent
        expr: ceil(100 - (100 * node_memory_MemAvailable_bytes /node_memory_MemTotal_bytes))
      - record: {{SERVICE}}_cpu_usage_percent
        expr: 100 - (avg by (instanceName) (rate(node_cpu_seconds_total{mode="idle"}[1m]) * 100 ))